version: "3.8"
services:
  proxy.envoy.localhost:
    image: envoyproxy/envoy:distroless-v1.29.2
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    command: ["-c /etc/envoy.yaml"]